export const LOAD_DESTINATION = "LOAD_DESTINATION";
export const FAIL_DESTINATION = "FAIL_DESTINATION";
export const GET_ALL_DESTINATIONS = "GET_ALL_DESTINATIONS";
export const CREATE_DESTINATION = "CREATE_DESTINATION";
export const UPDATE_DESTINATION = "UPDATE_DESTINATION";
export const DELETE_DESTINATION = "DELETE_DESTINATION";