export const LOAD_RESERVATION = "LOAD_RESERVATION";
export const FAIL_RESERVATION = "FAIL_RESERVATION";
export const GET_MY_RESERVATIONS = "GET_MY_RESERVATIONS";
export const GET_ALL_RESERVATIONS = "GET_ALL_RESERVATIONS";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const CANCEL_RESERVATION = "CANCEL_RESERVATION";
export const UPDATE_STATUT = "UPDATE_STATUT";
export const DELETE_RESERVATION = "DELETE_RESERVATION";